# Generated by Django 4.2.2 on 2023-06-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='agenda',
            name='data_fim',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='data_inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
