# Generated by Django 4.2.2 on 2023-06-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_local_alter_agenda_data_fim_alter_agenda_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
