# Generated by Django 4.2.2 on 2023-06-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_convidado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='convidados',
            field=models.ManyToManyField(to='agenda.convidado'),
        ),
        migrations.AlterField(
            model_name='convidado',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
